name: Run Jupyter Notebook Daily

on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression runs the script every day at midnight UTC.
  workflow_dispatch:     # Allows manual triggering of the workflow (for testing purposes)

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # This checks out the repository to get access to your code

    - name: Set up Python
      uses: actions/setup-python@v4  # Sets up Python for the workflow
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
        pip install jupyter 

    - name: Execute Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute Geomapper.ipynb --output Geomapper.ipynb
